root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "tmp/api"
  delay = 1000
  exclude_dir = ["tmp", "bin", ".git"]
  include_ext = ["go", "mod", "sum"]
  stop_on_error = true

[log]
  time = true
